version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  rails:
    image: pedroschmitt/ubuntu-rails-ssh:ruby-2.5.3
    volumes:
      - .:/projects
    ports:
      - "3001:3000"
      - "22"
    depends_on:
      - postgres
  
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"
  
  redis:
    image: 'redis:5.0.3'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis:

